name: Bug report
description: Report an issue with the library
labels: 'Type: Bug'
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Please provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: What steps do you have to take to reproduce the behavior?
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Add any other context about the problem here, such as screenshots or system specs.
    validations:
      required: false
